pipeline:
  identifier: Build_intersight_server_1704725342332
  name: Provision Intersight Server
  orgIdentifier: default
  projectIdentifier: CiscoLive
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: baelengit
        repoName: intersight-server
  stages:
    - type: Run
      name: Invoke Intersight Workflow
      identifier: Run_ico_wf
      spec:
        connectorRef: account.harnessImage
        image: python:latest
        shell: Sh
        command: |-
          echo "Welcome to Harness CI"
          uname -a
          pip install intersight
          pip install pytest-cov
          pip install -r requirements.txt

          pytest -v --cov --junitxml="result.xml" test_api.py test_api_2.py test_api_3.py

          echo "Done"
        reports:
          type: JUnit
          spec:
            paths:
              - "**/*.xml"
  tags: {}
